# Generated by Django 2.2 on 2022-11-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221113_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(default=0, max_length=10, unique=True)),
                ('gender', models.CharField(blank=True, choices=[(None, 'please select'), ('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('relative_address', models.TextField(blank=True, null=True)),
                ('relative_contact', models.CharField(default=0, max_length=10, unique=True)),
                ('serverity', models.CharField(blank=True, choices=[(None, 'please select'), ('High', 'High'), ('Low', 'Low')], default=None, max_length=20, null=True)),
                ('aadhaar_number', models.CharField(default='', max_length=12)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
