# Generated by Django 2.2 on 2022-11-14 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20221114_0929'),
        ('app', '0003_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='HospitalPatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(default=0, max_length=10, unique=True)),
                ('gender', models.CharField(blank=True, choices=[(None, 'please select'), ('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('relative_address', models.TextField(blank=True, null=True)),
                ('relative_contact', models.CharField(default=0, max_length=10, unique=True)),
                ('serverity', models.CharField(blank=True, choices=[(None, 'please select'), ('High', 'High'), ('Low', 'Low')], default=None, max_length=20, null=True)),
                ('aadhaar_number', models.CharField(default='', max_length=12)),
                ('bed_type', models.CharField(blank=True, choices=[(None, 'please select'), ('ICU', 'ICU'), ('Normal', 'Normal')], default=None, max_length=20, null=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='CareCenterPatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(default=0, max_length=10, unique=True)),
                ('gender', models.CharField(blank=True, choices=[(None, 'please select'), ('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('relative_address', models.TextField(blank=True, null=True)),
                ('relative_contact', models.CharField(default=0, max_length=10, unique=True)),
                ('serverity', models.CharField(blank=True, choices=[(None, 'please select'), ('High', 'High'), ('Low', 'Low')], default=None, max_length=20, null=True)),
                ('aadhaar_number', models.CharField(default='', max_length=12)),
                ('bed_type', models.CharField(blank=True, default='Normal', max_length=20, null=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('carecenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Carecenter')),
            ],
        ),
    ]
