# Generated by Django 2.2 on 2022-11-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221114_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='serverity',
            new_name='severity',
        ),
        migrations.AlterField(
            model_name='hospitalpatientdetails',
            name='bed_type',
            field=models.CharField(blank=True, choices=[(None, 'please select'), ('With oxygen', 'With oxygen'), ('Without oxygen', 'Without oxygen')], default=None, max_length=20, null=True),
        ),
    ]
