# Generated by Django 2.2 on 2022-11-14 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221114_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='username',
            new_name='patient_name',
        ),
        migrations.AddField(
            model_name='admission',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
