# Generated by Django 2.2 on 2022-11-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221114_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='patient_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='user_id',
        ),
    ]
