# Generated by Django 2.2 on 2022-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20221115_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('Uttaranchal', 'Uttaranchal'), ('Rajasthan', 'Rajasthan'), ('Maharashtra', 'Maharashtra'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Punjab', 'Punjab'), ('Jharkhand', 'Jharkhand'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala'), ('Orissa', 'Orissa'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Tamilnadu', 'Tamilnadu'), ('Gujarat', 'Gujarat'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand'), ('Madhya Pradesh', 'Madhya Pradesh')], default=None, max_length=100, null=True),
        ),
    ]
