# Generated by Django 2.2 on 2022-11-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_carecenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(blank=True, choices=[(None, 'please select'), ('Private', 'Private'), ('Government', 'Government')], default=1, max_length=20, null=True),
        ),
    ]
