# Generated by Django 2.2 on 2022-11-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20221113_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(blank=True, choices=[(None, 'please select'), ('Private', 'Private'), ('Government', 'Government')], default=None, max_length=20, null=True),
        ),
    ]
