# Generated by Django 2.2 on 2022-11-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20221114_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAvailabilty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(blank=True, max_length=250, null=True)),
                ('carecenter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Carecenter')),
                ('hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Hospital')),
            ],
        ),
    ]
