# Generated by Django 2.2 on 2022-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_seatavailabilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatavailabilty',
            name='available_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seatavailabilty',
            name='total_beds',
            field=models.IntegerField(default=0),
        ),
    ]
