# Generated by Django 2.2 on 2022-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20221114_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatavailabilty',
            name='carecenter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seatavailabilty',
            name='hospital_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
