# Generated by Django 2.2 on 2022-11-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20221114_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCenterSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('carecenter_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('hospital_id', models.IntegerField()),
            ],
        ),
    ]
